In [1]:
import pandas as pd
import numpy as np
import datetime

In [83]:
allergiesCSV = pd.read_csv("../data/allergies.csv")
observationsCSV = pd.read_csv("../data/observations.csv")
acsCSV = pd.read_csv("../data/ACS.csv")
careplansCSV = pd.read_csv("../data/careplans.csv")
encountersCSV = pd.read_csv("../data/encounters.csv")
immunizationsCSV = pd.read_csv("../data/immunizations.csv")
procedutesCSV = pd.read_csv("../data/procedures.csv")
zipCSV = pd.read_csv("../data/zip_to_zcta_2019.csv")
conditionsCSV = pd.read_csv("../data/conditions.csv")
medicationsCSV = pd.read_csv("../data/medications.csv")
patientsCSV = pd.read_csv("../data/patients.csv")

In [ ]:
match patient to patient
match date to date
take reason

In [77]:
emergency = encountersCSV.loc[(encountersCSV['CODE'] == 50849002)|(encountersCSV['CODE'] == 183460006)|(encountersCSV['CODE']==183478001)].copy()
emergency = emergency[emergency['DATE'].between('2008', '2017')]

In [78]:

for index,row in emergency.iterrows():
    if isinstance(row['REASONDESCRIPTION'],float):
        date = row['DATE']
        find = conditionsCSV[conditionsCSV['PATIENT'] == row['PATIENT']]
        reason = find[find['START'] == date]['DESCRIPTION']
        code = find[find['START'] == date]['CODE']
        try:
            emergency['REASONDESCRIPTION'][index] = reason.values[0]
            emergency['REASONCODE'][index] = code.values[0]
        except:
            emergency['REASONDESCRIPTION'][index] = np.nan
            emergency['REASONCODE'][index] = np.nan

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [45]:
print(np.isnan(emergency['REASONDESCRIPTION'][25]))

True

g = emergency[emergency['HouseholdIncome']<75000]
h = g[g['DeathDifference']<datetime.timedelta(days=200)]
j = h[h['DeathDifference']>datetime.timedelta(days=0)]
j['Zipcode'].unique()

In [165]:
j

,ID,DATE,PATIENT,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION,DeathDate,Death,DeathDifference,...,HouseholdIncome,HouseholdMOE,Zipcode,Age,YearDeath,Black,Hispanic,Asian,White,LowIncome
106,c3ecf43e-51b9-4783-b303-4cf2a2307fc7,2016-02-05,2c884d0f-62a1-4371-becc-36a98cdc4f52,185349003,Outpatient Encounter,NaN,NaN,2016-08-22,1,199 days,...,50426.0,2425.0,01604,96,1,0,1,0,0,1
258,2217aeaa-3074-40e8-9ec3-9dbebfe9d098,2011-05-28,6166101c-e02f-4230-b6c1-533865470674,185349003,Outpatient Encounter,NaN,NaN,2011-10-14,1,139 days,...,28590.0,3444.0,01104,96,1,0,0,0,1,1
496,5e1cc281-19a8-4dd3-bb03-7610739b405c,2016-11-18,99ca7d85-4dd4-446a-a200-b65a4dee5756,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2017-05-22,1,185 days,...,39670.0,13258.0,02111,63,1,0,1,0,0,1
497,38739637-b1af-4ee9-a4ce-a8894264b0e7,2016-12-10,99ca7d85-4dd4-446a-a200-b65a4dee5756,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2017-05-22,1,163 days,...,39670.0,13258.0,02111,63,1,0,1,0,0,1
1924,d8ed4921-783c-4e10-bbc9-e8dbd5913c20,2013-04-09,6d66c6a6-8b0d-47c0-a573-b78ec8ceec63,185349003,Outpatient Encounter,NaN,NaN,2013-05-01,1,22 days,...,65163.0,5214.0,01606,79,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19024,d086cedf-817c-4918-9a4b-699b815cc9fb,2016-11-11,26b5fb68-32a2-47fe-a1e4-12db200d5b68,50849002,Emergency room admission,4.446501e+07,Sprain of ankle,2017-01-25,1,75 days,...,73280.0,5522.0,02171,90,1,0,1,0,0,0
19144,21f555bd-d264-4f01-ab9f-554c768f2d83,2015-12-15,093c5b43-9b43-40a4-8cb6-ba2292cba7c0,185349003,Outpatient Encounter,NaN,NaN,2016-03-06,1,82 days,...,73322.0,6654.0,02141,98,1,1,0,0,0,0
20343,bd341b34-b178-4a6c-bbc7-564242d11512,2012-11-03,2bbaedc8-d765-4950-bfc2-32b16713934c,185349003,Outpatient Encounter,NaN,NaN,2013-01-25,1,83 days,...,70078.0,16520.0,01128,91,1,0,1,0,0,0
20344,9c0cd96f-9048-4fd9-af65-4a8b3748beac,2012-11-21,2bbaedc8-d765-4950-bfc2-32b16713934c,50849002,Emergency room admission,6.596600e+07,Fracture of forearm,2013-01-25,1,65 days,...,70078.0,16520.0,01128,91,1,0,1,0,0,0
20345,736e13f7-4dc5-4e49-8e0e-2e28115fca12,2013-01-05,2bbaedc8-d765-4950-bfc2-32b16713934c,185349003,Encounter for 'check-up',6.596600e+07,Fracture of forearm,2013-01-25,1,20 days,...,70078.0,16520.0,01128,91,1,0,1,0,0,0

In [84]:
massZipCSV = zipCSV[zipCSV.STATE == "MA"]
zipAndIncome = massZipCSV.merge(acsCSV,left_on='ZCTA', right_on='GEO.id2')
zipAndIncome = zipAndIncome.replace(['2,500-',"***",'-','**'],-1)
zaiMerge = zipAndIncome.copy().drop(['ZIP_CODE','PO_NAME','STATE','ZIP_TYPE','zip_join_type','GEO.id','GEO.id2','GEO.display-label'],axis=1)

zaiMerge['HouseholdIncome'] = zipAndIncome['HC01_EST_VC13'].astype(int)
zaiMerge['HouseholdMOE'] = zipAndIncome['HC01_MOE_VC13'].astype(int)
zaiMerge['Family'] = zipAndIncome[['HC02_EST_VC13','HC02_MOE_VC13']].values.tolist()
zaiMerge['Married'] = zipAndIncome[['HC03_EST_VC13','HC03_MOE_VC13']].values.tolist()
zaiMerge['Nonfamily'] = zipAndIncome[['HC04_EST_VC13','HC04_MOE_VC13']].values.tolist()
zaiMerge = zaiMerge.drop(['HC01_EST_VC13','HC01_MOE_VC13','HC02_EST_VC13','HC02_MOE_VC13','HC03_EST_VC13','HC03_MOE_VC13','HC04_EST_VC13','HC04_MOE_VC13'],axis=1)


patientsCSV['BirthPO'] = patientsCSV['BIRTHPLACE'].map(lambda x: str(x)[0:-6])
patientsCSV['HomeZip'] = patientsCSV['ADDRESS'].map(lambda x:'0'+str(x)[-7:-3])
patientsCSV = patientsCSV.drop(['Unnamed: 0', 'SSN','DRIVERS','PASSPORT','PREFIX','FIRST', 'LAST', 'SUFFIX', 'MAIDEN'],axis=1)    #removed data to clean data and make it visually easier to understand and to ensure privacy

patientsCSV['HouseholdIncome'] = patientsCSV['HomeZip'].map(lambda x: np.nan if x =='0' or x not in zaiMerge['ZCTA'].unique() else zaiMerge.loc[zaiMerge['ZCTA']== x]['HouseholdIncome'].values[0])
patientsCSV['HouseholdMOE'] = patientsCSV['HomeZip'].map(lambda x: np.nan if x =='0' or x not in zaiMerge['ZCTA'].unique() else zaiMerge.loc[zaiMerge['ZCTA']== x]['HouseholdMOE'].values[0])
patientsCSV['Family'] = patientsCSV['HomeZip'].map(lambda x: np.nan if x =='0'or x not in zaiMerge['ZCTA'].unique() else zaiMerge.loc[zaiMerge['ZCTA']== x]['Family'].values[0])
patientsCSV['Married'] = patientsCSV['HomeZip'].map(lambda x: np.nan if x =='0'or x not in zaiMerge['ZCTA'].unique() else zaiMerge.loc[zaiMerge['ZCTA']== x]['Married'].values[0])
patientsCSV['Nonfamily'] = patientsCSV['HomeZip'].map(lambda x: np.nan if x =='0'or x not in zaiMerge['ZCTA'].unique() else zaiMerge.loc[zaiMerge['ZCTA']== x]['Nonfamily'].values[0])
patientsCSV['DEATHDATE'] = patientsCSV['DEATHDATE'].fillna(0) 

emergency = pd.read_csv("../data/encounters.csv")

emergency = emergency[emergency['DATE'].between('2008', '2017')]
emergency['DeathDate'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['DEATHDATE'].values[0])

emergency['Death'] = emergency['DeathDate'].map(lambda x: 0 if x == 0 else 1)

for index,row in emergency.iterrows():
    if isinstance(row['REASONDESCRIPTION'],float):
        date = row['DATE']
        find = conditionsCSV[conditionsCSV['PATIENT'] == row['PATIENT']]
        reason = find[find['START'] == date]['DESCRIPTION']
        code = find[find['START'] == date]['CODE']
        try:
            emergency['REASONDESCRIPTION'][index] = reason.values[0]
            emergency['REASONCODE'][index] = code.values[0]
        except:
            emergency['REASONDESCRIPTION'][index] = np.nan
            emergency['REASONCODE'][index] = np.nan

emergency['DATE']=pd.to_datetime(emergency['DATE'])
emergency['DeathDate']=pd.to_datetime(emergency['DeathDate'])

emergency['DeathDifference'] = emergency['DeathDate']-emergency['DATE']
emergency['Race'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['RACE'].values[0])

emergency['HouseholdIncome'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['HouseholdIncome'].values[0])
emergency['HouseholdMOE'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['HouseholdMOE'].values[0])
emergency['Zipcode'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['HomeZip'].values[0])
emergency['Age'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['AGE'].values[0])
#emergency['Family'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['Family'].values[0])
#emergency['Married'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['Married'].values[0])
#emergency['Nonfamily'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['Nonfamily'].values[0])
#emergency['Marital'] = emergency['PATIENT'].map(lambda x: patientsCSV.loc[patientsCSV['ID']==x]['MARITAL'].values[0])


emergency = emergency.drop('Unnamed: 0', axis=1)
emergency['YearDeath'] = emergency['DeathDifference'].map(lambda x: 1 if datetime.timedelta(days=0)<=x<=datetime.timedelta(days=365) else 0)

emergency['Black'] = emergency['Race'].map(lambda x: 1 if x == 'black or african american' or x=='black' else 0)
emergency['Hispanic'] = emergency['Race'].map(lambda x: 1 if x == 'hispanic' else 0)
emergency['Asian'] = emergency['Race'].map(lambda x: 1 if x == 'asian' else 0)
emergency['White'] = emergency['Race'].map(lambda x: 1 if x == 'white' else 0)

emergency['LowIncome'] = emergency['HouseholdIncome'].map(lambda x: 1 if x < 62533.6 else 0)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [144]:

g = emergency[emergency['DeathDifference']<datetime.timedelta(days=100)]
g[g['DeathDifference']>datetime.timedelta(days=0)].head(30).tail(20)

,ID,DATE,PATIENT,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION,DeathDate,Death,DeathDifference,...,HouseholdIncome,HouseholdMOE,Zipcode,Age,YearDeath,Black,Hispanic,Asian,White,LowIncome
4974,36353701-62e8-4caa-a99b-e7e1b078333b,2010-05-16,304ef151-bcfb-4f05-94f3-a7598efac77e,185347001,Encounter for problem,NaN,NaN,2010-07-05,1,50 days,...,61527.0,3051.0,02302,56,1,0,1,0,0,1
4975,7ed48280-f6e4-4c46-a554-bda3414579a5,2010-06-13,304ef151-bcfb-4f05-94f3-a7598efac77e,185347001,Encounter for problem,NaN,NaN,2010-07-05,1,22 days,...,61527.0,3051.0,02302,56,1,0,1,0,0,1
5707,d15e6de5-e296-4cf3-9037-2c854974654b,2015-05-02,045e2f8e-5bbd-4776-9a84-43ba02cea3ba,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2015-08-09,1,99 days,...,149414.0,13588.0,02421,55,1,0,1,0,0,0
5708,da6927d5-ceb8-423a-abc9-5a8248719546,2015-05-24,045e2f8e-5bbd-4776-9a84-43ba02cea3ba,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2015-08-09,1,77 days,...,149414.0,13588.0,02421,55,1,0,1,0,0,0
5709,526148c9-dae5-45b7-9ffc-41a32b813019,2015-06-17,045e2f8e-5bbd-4776-9a84-43ba02cea3ba,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2015-08-09,1,53 days,...,149414.0,13588.0,02421,55,1,0,1,0,0,0
5710,2d3f8cfb-3850-48d9-bc37-b8f3f3b38dbd,2015-07-14,045e2f8e-5bbd-4776-9a84-43ba02cea3ba,185347001,Encounter for problem,6.784100e+13,Primary small cell malignant neoplasm of lung ...,2015-08-09,1,26 days,...,149414.0,13588.0,02421,55,1,0,1,0,0,0
5761,508aebb9-5b6c-42fc-990d-3f399b7ba386,2011-11-02,90e7f959-f0ec-4e9e-bce8-ca0a7d0e6a1f,185349003,Outpatient Encounter,NaN,NaN,2011-11-12,1,10 days,...,73117.0,5809.0,01757,86,1,0,1,0,0,0
6063,e7d1b9ab-a5c4-4d0b-ac86-f6582496195e,2014-01-25,cdbe1927-b954-4f37-9294-ac0ca277d147,34285007,Hospital admission,2.336040e+08,Pneumonia,2014-02-06,1,12 days,...,NaN,NaN,02283,92,1,0,1,0,0,0
6821,04e0b540-cfaf-4875-895f-8cdb3235a48e,2008-06-20,6ddea441-48d4-4ef1-8213-04ca25c78497,185349003,Outpatient Encounter,NaN,NaN,2008-07-24,1,34 days,...,60045.0,3083.0,02148,84,1,0,1,0,0,1
6850,9f7ccaa9-e5b9-4da1-a2f0-c527eb704e1f,2009-01-09,6f45458c-8658-449d-a583-effa43cbd8a8,185349003,Outpatient Encounter,NaN,NaN,2009-03-21,1,71 days,...,100158.0,6556.0,01821,87,1,0,1,0,0,0
6851,4f64dddf-122d-4da0-9b4b-eeaf7e1e0f83,2009-02-11,6f45458c-8658-449d-a583-effa43cbd8a8,185345009,Encounter for symptom,1.956620e+08,Acute viral pharyngitis (disorder),2009-03-21,1,38 days,...,100158.0,6556.0,01821,87,1,0,1,0,0,0
7120,977f504f-1ec5-45c7-aa16-b0010a62745f,2015-02-02,8b3cf0c5-affd-4cbb-a397-e63484ba4d47,34285007,Hospital admission,2.336040e+08,Pneumonia,2015-02-15,1,13 days,...,80709.0,4548.0,02379,78,1,0,0,1,0,0
7207,0478e6e0-a81c-4c21-9055-002ce3e1575b,2012-12-16,ca805fdc-5763-4140-977c-0b84eec8c41d,185345009,Encounter for symptom,4.448140e+08,Viral sinusitis (disorder),2013-02-25,1,71 days,...,44873.0,2290.0,02301,90,1,0,1,0,0,1
8214,f7ed1acc-4603-4a2e-98c9-d334e1ff07ee,2013-07-31,353c5ff1-6970-4dba-ae96-1f69fb02f23e,698314001,Consultation for treatment,NaN,NaN,2013-11-05,1,97 days,...,73085.0,7942.0,01267,48,1,0,1,0,0,0
8834,5d398e0f-52d9-4fda-bc8e-06f85e62d3a6,2015-01-22,44c77449-072b-4559-8608-dc28f4647379,185347001,Encounter for problem,NaN,NaN,2015-04-20,1,88 days,...,44873.0,2290.0,02301,58,1,0,1,0,0,1
8835,db011f23-44a7-4cde-8390-95b5c644ba90,2015-02-24,44c77449-072b-4559-8608-dc28f4647379,185347001,Encounter for problem,NaN,NaN,2015-04-20,1,55 days,...,44873.0,2290.0,02301,58,1,0,1,0,0,1
8836,3eef87a7-2890-4487-ad5e-1fc968f306ea,2015-03-26,44c77449-072b-4559-8608-dc28f4647379,185347001,Encounter for problem,NaN,NaN,2015-04-20,1,25 days,...,44873.0,2290.0,02301,58,1,0,1,0,0,1
9353,d4f63601-f3ef-4d14-b82f-59709f5ff319,2014-02-01,de5deae8-3379-4bd1-8cf7-e48b5e61212b,185347001,Encounter for problem,NaN,NaN,2014-05-04,1,92 days,...,70873.0,6371.0,01535,58,1,0,1,0,0,0
9354,c72862c0-e176-4857-90e4-d5e37b2f2e8f,2014-03-02,de5deae8-3379-4bd1-8cf7-e48b5e61212b,185347001,Encounter for problem,NaN,NaN,2014-05-04,1,63 days,...,70873.0,6371.0,01535,58,1,0,1,0,0,0
9355,87b6f13b-95b3-4801-8ba8-ed5cec862fb5,2014-03-31,de5deae8-3379-4bd1-8cf7-e48b5e61212b,185347001,Encounter for problem,NaN,NaN,2014-05-04,1,34 days,...,70873.0,6371.0,01535,58,1,0,1,0,0,0

INFLUENZA IMMUNIZATION STAT

In [86]:
flu = immunizationsCSV[immunizationsCSV['CODE'] == 140]
patients = flu['PATIENT'].unique()
patientsCSV['Flu'] = patientsCSV['ID'].map(lambda x: 1 if x in patients else 0)

In [98]:
patientsCSV[patientsCSV['Flu']==0]
patientsCSV['RACE'].unique()

array(['hispanic', 'asian', 'black', 'white', 'black or african american'],
      dtype=object)

patientsCSV

In [99]:
patientsCSV[patientsCSV['RACE']=='black or african american']

,ID,BIRTHDATE,DEATHDATE,MARITAL,RACE,GENDER,BIRTHPLACE,ADDRESS,AGE,BirthPO,HomeZip,HouseholdIncome,HouseholdMOE,Family,Married,Nonfamily,Flu
17,1131717c-e009-446d-b353-0b865cbb4194,1/20/32,0,M,black or african american,F,Springfield MA US,4315 Sawayn Port Greenfield Town MA 01302 US,85,Springfield,01302,NaN,NaN,NaN,NaN,NaN,1
22,86fc9c5b-ce25-4f37-850b-697fcd3256c1,8/23/90,0,M,black or african american,M,Freetown MA US,126 Van Creek Freetown MA 02717 US,27,Freetown,02717,81335.0,11690.0,"[94250, 14063]","[103571, 13502]","[-1, -1]",1
31,17ac2a91-9629-4c6f-bbb4-9e462a453216,3/28/90,0,M,black or african american,F,Worcester MA US,28699 Douglas Fields Apt. 371 Rowley MA 01969 US,27,Worcester,01969,85496.0,6992.0,"[115921, 26144]","[125698, 15975]","[23417, 17472]",1
45,a7c79f2a-026b-478a-ada4-060c584a8b12,8/20/17,12/9/02,M,black or african american,M,Brockton MA US,NaN,100,Brockton,0,NaN,NaN,NaN,NaN,NaN,0
70,10fd692e-fdef-4aa6-b010-8a95005b59f1,1/16/12,0,NaN,black or african american,M,North Attleborough MA US,83477 Reinger Dam Boston MA 02297 US,5,North Attleborough,02297,NaN,NaN,NaN,NaN,NaN,1
97,2ff59946-e6d0-492e-8704-a98296eedd4c,11/24/97,5/22/17,NaN,black or african american,M,Pembroke MA US,88112 Destiney Viaduct Suite 807 Sandwich MA 0...,20,Pembroke,02563,82041.0,11680.0,"[99511, 13924]","[109742, 11795]","[39792, 11456]",1
104,7a7d1ba4-2e57-4c55-81e6-1f3a37da6645,12/15/05,0,NaN,black or african american,F,Shrewsbury MA US,9187 Dion Overpass Chelmsford MA 01824 US,12,Shrewsbury,01824,109638.0,6103.0,"[130830, 6222]","[135073, 3998]","[48730, 9390]",1
144,18e9f2ff-e9a9-48f4-a129-4a0e5c80c610,2/3/05,0,NaN,black or african american,F,Haverhill MA US,6149 MacGyver Passage Apt. 355 Andover MA 0181...,12,Haverhill,01810,134627.0,6226.0,"[160794, 9239]","[180744, 7713]","[53608, 4770]",1
147,e489813c-d670-4b7c-9ee2-fb13f40caac1,3/14/13,0,NaN,black or african american,F,Freetown MA US,42895 Edmond Drives Townsend MA 01474 US,4,Freetown,01474,98221.0,19693.0,"[133594, 23116]","[138846, 14695]","[46905, 30029]",1
195,f9a49fd7-d784-4081-a537-7219edab2bfb,1/12/36,6/1/08,M,black or african american,F,Methuen Town MA US,903 Murazik Skyway Suite 446 Lowell MA 01850 US,81,Methuen Town,01850,42437.0,6212.0,"[47054, 9430]","[76450, 6430]","[24978, 8404]",1
277,6c713e1c-543e-41c9-ae98-fe753d3c50fe,6/17/31,9/26/07,M,black or african american,F,Woburn MA US,88380 Koepp Ramp Boston MA 02109 US,86,Woburn,02109,117344.0,23290.0,"[174500, 21963]","[180382, 31235]","[93125, 17493]",0
315,cda9a70b-87da-4fd1-87f9-9563be88e492,2/11/72,0,S,black or african american,F,Mattapoisett MA US,171 Schimmel Crest Lynn MA O1902 US,45,Mattapoisett,01902,39654.0,2689.0,"[46153, 4651]","[69798, 6062]","[23527, 4994]",1
347,7ae6f089-97ca-457e-ab59-f6ab0599c886,8/7/27,8/27/00,M,black or african american,F,Quincy MA US,NaN,90,Quincy,0,NaN,NaN,NaN,NaN,NaN,0
381,0fb7f3f3-8473-4ae1-a057-32b104337236,11/13/16,0,NaN,black or african american,M,Brewster MA US,311 Dexter Trace Worcester MA 01603 US,1,Brewster,01603,40967.0,4581.0,"[53231, 6613]","[61615, 11846]","[26807, 4326]",1
425,e7a34cde-5edd-49c3-94d1-8e351e3375da,10/31/51,12/31/03,M,black or african american,F,Milton MA US,9339 Hessel Oval Chicopee MA O1013 US,66,Milton,01013,40876.0,2642.0,"[48772, 3728]","[66348, 7501]","[30213, 5675]",0
444,51bdda68-3dd2-49b6-9db5-87b043f42872,3/8/49,2/27/51,NaN,black or african american,M,Pittsfield MA US,46101 Auer Path Apt. 621 Georgetown MA 01833 US,68,Pittsfield,01833,106016.0,11766.0,"[127212, 7729]","[134063, 10166]","[46625, 6965]",0
493,3a33ad14-8b02-4e89-b3c5-d8c7715cd5a5,11/1/52,0,M,black or african american,F,Dover MA US,847 Funk Branch Lynn MA 01903 US,65,Dover,01903,NaN,NaN,NaN,NaN,NaN,1
530,29f9a670-062f-4937-a639-cd54c42e98b4,1/26/62,0,M,black or african american,F,Peabody MA US,2271 Volkman Springs Holden MA 01520 US,55,Peabody,01520,99575.0,6149.0,"[116681, 5858]","[123818, 7778]","[52069, 10363]",1
617,0e708a73-1e4b-491f-9d3f-c0c3e291081c,8/18/32,5/12/11,M,black or african american,F,Yarmouth MA US,82793 Lilyan Islands Suite 821 Monson MA 01057 US,85,Yarmouth,01057,74439.0,6672.0,"[86181, 7245]","[95565, 7511]","[45815, 10843]",1
620,7fc7b9d4-141b-4fff-ae19-68889718b438,5/8/28,1/12/10,M,black or african american,F,Stoneham MA US,381 Bartell Islands Suite 549 Newton MA 02467 US,89,Stoneham,02467,108413.0,7579.0,"[148281, 18509]","[175038, 23017]","[62232, 10881]",1
797,b696c7d0-610e-4381-ba68-5836d9217d6b,6/1/78,0,M,black or african american,M,Cambridge MA US,2070 Rhianna Street Weymouth Town MA 02190 US,39,Cambridge,02190,80139.0,4598.0,"[97853, 6289]","[106813, 11820]","[49904, 8896]",1
800,deb7aad1-1596-44f7-b603-7e04d3306845,11/12/63,0,M,black or african american,F,Gloucester MA US,59281 Yazmin Pass Wellesley MA 02481 US,54,Gloucester,02481,179655.0,7450.0,"[215291, 25715]","[234559, 16469]","[93819, 20143]",1
808,b7902ae0-ce01-41ee-ae1b-b3fc88eed4be,5/7/32,0,M,black or african american,F,Easton MA US,76156 Laisha Stream Winchester MA 01890 US,85,Easton,01890,149321.0,13377.0,"[182264, 13031]","[192589, 12760]","[52431, 5463]",1
821,9fdc58d1-742d-4b60-8513-c676f647b39a,8/7/37,0,M,black or african american,F,Watertown Town MA US,649 Davis Mall Beverly MA 01915 US,80,Watertown Town,01915,73839.0,3871.0,"[98151, 5565]","[115603, 5812]","[39490, 5677]",1
842,49bb8d33-d013-46dd-b72a-de0d207f98c5,8/25/93,0,NaN,black or african american,F,Arlington MA US,19200 Audreanne Terrace Apt. 816 Canton MA 020...,24,Arlington,02021,93672.0,6439.0,"[123250, 8834]","[140500, 13018]","[53851, 14266]",1
912,5ead9280-1716-4793-85dd-d1070b94f1d3,12/5/21,10/3/94,M,black or african american,M,Boston MA US,8474 Toni Lodge Apt. 669 Walpole MA 02081 US,96,Boston,02081,95592.0,10366.0,"[117672, 10794]","[130996, 13280]","[48819, 6499]",0
992,23cc6bc8-5bfc-4c1e-902c-e7cb01a6c44c,4/1/93,0,NaN,black or african american,M,Haverhill MA US,96825 Catalina Spurs Suite 351 Westminster MA ...,24,Haverhill,01441,NaN,NaN,NaN,NaN,NaN,1
998,79cbdef8-fcef-4107-bf50-2b79bec4d438,7/28/30,7/4/77,M,black or african american,M,Cambridge MA US,6242 Ritchie Throughway Plymouth MA 02360 US,87,Cambridge,02360,80905.0,3154.0,"[97237, 3800]","[108876, 5108]","[46357, 4019]",0
1039,9ef5a5d3-e6f7-40f7-a50f-08cad9a0e782,10/23/61,0,S,black or african american,F,Quincy MA US,50611 Keebler Summit Franklin Town MA 02038 US,56,Quincy,02038,108815.0,6951.0,"[127639, 9028]","[140903, 7323]","[43889, 12074]",1
1092,fc94c4b3-a114-4c28-a8e8-0f890b674b22,9/8/51,0,M,black or african american,M,Brookline MA US,2891 Weber Centers North Andover MA 01845 US,66,Brookline,01845,102008.0,5376.0,"[129578, 6371]","[141446, 9286]","[42148, 10240]",1
1142,e281fb98-d32b-46d4-8568-bf1c21add34a,11/2/36,6/21/10,M,black or african american,F,Lynn MA US,449 Emmerich Roads Apt. 540 Westwood MA 02090 US,81,Lynn,02090,140355.0,16254.0,"[161113, 11000]","[175385, 16138]","[47230, 5333]",1
1177,d4841577-f9ac-4cc8-ad03-f80131552fc9,4/10/25,0,M,black or african american,F,Shirley MA US,72820 Rosenbaum Underpass Boston MA O2111 US,92,Shirley,02111,39670.0,13258.0,"[47321, 20869]","[49063, 28130]","[38545, 16109]",1
1256,bcc6577e-d51a-4071-9f22-ccb45f6db2f3,12/18/36,0,S,black or african american,M,Plymouth MA US,808 Kylie Points Pittsfield MA 01203 US,81,Plymouth,01203,NaN,NaN,NaN,NaN,NaN,1
1312,3247fb56-d8af-450e-a370-926636c1daa2,4/5/69,0,M,black or african american,F,Becket MA US,8039 Green Shoal Scituate MA 02066 US,48,Becket,02066,110492.0,11277.0,"[135194, 9651]","[152557, 14978]","[34919, 4746]",1
1393,6d980fe6-d187-4e36-b889-4f5f508c8f8c,10/1/69,0,S,black or african american,M,Peabody MA US,760 Sonny Mills Apt. 491 Wellesley MA 02481 US,48,Peabody,02481,179655.0,7450.0,"[215291, 25715]","[234559, 16469]","[93819, 20143]",1
1395,dd65ebe4-36fa-4c1b-85d9-1e54bee79917,8/29/64,0,M,black or african american,M,Boston MA US,715 Konopelski Plains Apt. 350 Plymouth MA 023...,53,Boston,02362,NaN,NaN,NaN,NaN,NaN,1
1406,e757c343-8bf6-4ead-986e-64d40a270032,6/11/74,0,S,black or african american,F,Adams MA US,94074 Greenholt View Apt. 914 Blackstone MA 01...,43,Adams,01504,75544.0,4626.0,"[93500, 6294]","[107258, 9058]","[33903, 6954]",1
1413,fe481b96-8643-457f-bee3-2679c93e92b0,11/21/21,12/13/04,S,black or african american,M,Newburyport MA US,5221 Schneider Causeway Suite 675 Boston MA 02...,96,Newburyport,02298,NaN,NaN,NaN,NaN,NaN,0
1437,69414e22-d080-4468-b13f-8f3531312ae9,4/10/06,0,NaN,black or african american,F,Boston MA US,346 Breana Prairie Hubbardston MA 01452 US,11,Boston,01452,84803.0,7281.0,"[94512, 5748]","[96676, 10600]","[41471, 19862]",1

In [94]:
patientsCSV.shape[0]

1462

In [134]:
fluPeople = patientsCSV[patientsCSV['Flu']==0]
fluPeople[fluPeople['RACE']=='hispanic']

,ID,BIRTHDATE,DEATHDATE,MARITAL,RACE,GENDER,BIRTHPLACE,ADDRESS,AGE,BirthPO,HomeZip,HouseholdIncome,HouseholdMOE,Family,Married,Nonfamily,Flu
7,443a0255-5584-45d9-93ca-9174f1d45f03,5/12/33,4/13/98,S,hispanic,M,Easton MA US,7134 Schmitt Passage Suite 889 Cambridge MA 02...,84,Easton,02141,73322.0,6654.0,"[89183, 9819]","[108021, 16532]","[57650, 10170]",0
11,16077486-5747-4abe-8321-ba290fb7197c,12/28/53,8/21/98,S,hispanic,F,Seekonk MA US,77237 Bernadette Turnpike Boston MA 02118 US,64,Seekonk,02118,59589.0,8491.0,"[80707, 24230]","[175833, 26762]","[53020, 6646]",0
13,6a569777-9dec-4269-93e7-fefbcf21507f,4/1/48,10/21/04,M,hispanic,M,Chicopee MA US,875 Beulah Circles Apt. 780 Brookline MA 02447 US,69,Chicopee,02447,NaN,NaN,NaN,NaN,NaN,0
16,17cb551b-b45a-48eb-a097-6421b8bc0fb4,2/19/47,2/28/07,S,hispanic,M,Pembroke MA US,4368 Veum Shoals Suite 387 Worcester MA 01654 US,70,Pembroke,01654,NaN,NaN,NaN,NaN,NaN,0
19,c8e8ead2-352c-43bb-ae76-b80d74e23d05,9/17/24,5/28/80,S,hispanic,F,Norwood MA US,4668 Ebony Shores Suite 274 Dennis MA 02638 US,93,Norwood,02638,69375.0,7063.0,"[82083, 12193]","[86458, 12152]","[37155, 11494]",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,7d15ff47-9229-47db-80b4-98ab3d4ff7f0,1/14/47,11/8/49,NaN,hispanic,F,Gardner MA US,619 Conn Radial Suite 195 Adams MA 01220 US,70,Gardner,01220,48422.0,3201.0,"[63394, 3741]","[74837, 10318]","[34560, 3102]",0
1427,3e556436-09fb-4548-af34-9db1a14e4d37,6/29/17,0,NaN,hispanic,M,Winthrop Town MA US,685 Bonita Tunnel Cohasset MA 02025 US,0,Winthrop Town,02025,128224.0,19662.0,"[151528, 23161]","[166801, 26619]","[36442, 29207]",0
1431,65a4143c-8250-4954-9479-4c11eee01a43,6/30/18,8/19/45,M,hispanic,M,Bellingham MA US,47118 Marvin Flat Methuen Town MA 01844 US,99,Bellingham,01844,72664.0,4329.0,"[87373, 5547]","[100877, 3930]","[35333, 5651]",0
1441,0860636f-285a-4770-aadb-534a77464e37,8/16/20,8/10/98,M,hispanic,M,Bridgewater MA US,20787 Ryan Overpass Suite 462 Newburyport MA 0...,97,Bridgewater,01951,93040.0,14243.0,"[108167, 19646]","[113019, 15411]","[61563, 18712]",0
1455,68fc72e7-c155-4333-9af6-89f97c996741,7/27/51,10/25/02,M,hispanic,M,Wareham MA US,17454 Stone Crescent Saugus MA 01906 US,66,Wareham,01906,78372.0,5171.0,"[92181, 6765]","[102015, 4069]","[37722, 5977]",0